# Limpieza y preprocesamiento de datos

## Ingesta

In [3]:
# Recuperación de contenido del archivo CSV y creación de un DataFrame de pandas
import pandas as pd

# Cargar el archivo CSV en un DataFrame
df = pd.read_csv('retail_x_clientes.csv')
df

,customer_id,edad,ingresos,ciudad,fecha_ultima_compra,num_compras,deuda,churn
0,1860,50,23962.22,Ciudad de México,2023-08-30,4,5365.92,1.0
1,4772,49,NaN,puebla,2023-06-05,5,4692.15,1.0
2,4092,17,NaN,CDMX,2022-11-29,9,4617.36,1.0
3,1466,40,NaN,Puebla,2021-10-09,5,2101.78,0.0
4,5426,21,9998.37,Ciudad de México,2023-09-02,3,-1798.42,0.0
...,...,...,...,...,...,...,...,...
9995,5931,43,14059.39,CDMX,2021-07-31,6,2035.49,0.0
9996,2691,31,9851.20,CDMX,2022-01-17,4,4674.32,1.0
9997,5550,15,17832.33,México D.F.,2021-02-10,1,6148.24,1.0
9998,5408,44,13644.92,Puebla,2021-10-30,2,3710.74,1.0
9999,1227,42,NaN,Puebla,2024-02-24,6,2112.72,1.0

## Identificación de características generales del conjunto de datos

En esta fase, se realiza una inspección general de la estructura del conjunto de datos con el objetivo de identificar características generales con número de items, tipos de datos, datos nulos, items etiquetados/ no etiquetados, entre otras.

In [4]:
# Recuperando una muestra de los datos para inspección
df.head()

,customer_id,edad,ingresos,ciudad,fecha_ultima_compra,num_compras,deuda,churn
0,1860,50,23962.22,Ciudad de México,2023-08-30,4,5365.92,1.0
1,4772,49,NaN,puebla,2023-06-05,5,4692.15,1.0
2,4092,17,NaN,CDMX,2022-11-29,9,4617.36,1.0
3,1466,40,NaN,Puebla,2021-10-09,5,2101.78,0.0
4,5426,21,9998.37,Ciudad de México,2023-09-02,3,-1798.42,0.0

In [5]:
df.tail()

,customer_id,edad,ingresos,ciudad,fecha_ultima_compra,num_compras,deuda,churn
9995,5931,43,14059.39,CDMX,2021-07-31,6,2035.49,0.0
9996,2691,31,9851.20,CDMX,2022-01-17,4,4674.32,1.0
9997,5550,15,17832.33,México D.F.,2021-02-10,1,6148.24,1.0
9998,5408,44,13644.92,Puebla,2021-10-30,2,3710.74,1.0
9999,1227,42,NaN,Puebla,2024-02-24,6,2112.72,1.0

In [6]:
# Visualización de información general del DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          10000 non-null  int64
 1   edad                 10000 non-null  int64
 2   ingresos             7000 non-null   float64
 3   ciudad               10000 non-null  str
 4   fecha_ultima_compra  10000 non-null  str
 5   num_compras          10000 non-null  int64
 6   deuda                10000 non-null  float64
 7   churn                8999 non-null   float64
dtypes: float64(3), int64(3), str(2)
memory usage: 625.1 KB

Derivado de la observación que se ha realizado a través de las muestras proporcionadas por .head() y por .tail(), además de la la tarjeta informativa del dataframe se han realizado los siguientes hallazgos:
- En el caso de *ciudad* algunas denominaciones hacen referencia a la misma ubicación, específicamente: CDMX, Ciudad de México, México D.F.
- En el caso de *fecha_ultima_compra* se ha identificado que el tipo de dato es cadena y no *date*, esto afecta el filtrado del contenido a través de marcas de tiempo.
- Con respecto a *ingresos* y *churn* se puede observar que hay un faltante de datos de 3000 y 1001 datos respectivamente.

## Tratamiento de los datos duplicados

In [7]:
# Identificación de los valores duplicados en el DataFrame
df[df.duplicated(subset=['customer_id'])].count()

customer_id            5719
edad                   5719
ingresos               3963
ciudad                 5719
fecha_ultima_compra    5719
num_compras            5719
deuda                  5719
churn                  5132
dtype: int64